<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="144238" started-at="2018-08-05T02:07:42Z" finished-at="2018-08-05T02:10:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="144238" started-at="2018-08-05T02:07:42Z" finished-at="2018-08-05T02:10:06Z">
      <class name="com.crm.qa.test.LogInTest">
        <test-method status="PASS" signature="SetUp()[pri:0, instance:com.crm.qa.test.LogInTest@3e6fa38a]" name="SetUp" is-config="true" duration-ms="104505" started-at="2018-08-05T02:07:42Z" finished-at="2018-08-05T02:09:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="FAIL" signature="validateLoginPageTitle()[pri:1, instance:com.crm.qa.test.LogInTest@3e6fa38a]" name="validateLoginPageTitle" duration-ms="2216" started-at="2018-08-05T02:09:27Z" finished-at="2018-08-05T02:09:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Free CRM software in the cloud powers sales and customer service] but found [#1 Free CRM software in the cloud for sales and service]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Free CRM software in the cloud powers sales and customer service] but found [#1 Free CRM software in the cloud for sales and service]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.crm.qa.test.LogInTest.validateLoginPageTitle(LogInTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginPageTitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.crm.qa.test.LogInTest@3e6fa38a]" name="tearDown" is-config="true" duration-ms="1705" started-at="2018-08-05T02:09:29Z" finished-at="2018-08-05T02:09:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="SetUp()[pri:0, instance:com.crm.qa.test.LogInTest@3e6fa38a]" name="SetUp" is-config="true" duration-ms="11002" started-at="2018-08-05T02:09:31Z" finished-at="2018-08-05T02:09:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="PASS" signature="EnterLoginPage()[pri:2, instance:com.crm.qa.test.LogInTest@3e6fa38a]" name="EnterLoginPage" duration-ms="23067" started-at="2018-08-05T02:09:42Z" finished-at="2018-08-05T02:10:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EnterLoginPage -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.crm.qa.test.LogInTest@3e6fa38a]" name="tearDown" is-config="true" duration-ms="934" started-at="2018-08-05T02:10:05Z" finished-at="2018-08-05T02:10:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.crm.qa.test.LogInTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
